# Generated by Django 4.0.3 on 2022-04-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
